;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Correct",DevComment="")
+GameplayTagList=(Tag="Action.Hide",DevComment="")
+GameplayTagList=(Tag="Action.Intimidate",DevComment="")
+GameplayTagList=(Tag="Action.Ok",DevComment="")
+GameplayTagList=(Tag="Action.Protect",DevComment="")
+GameplayTagList=(Tag="Method.Correct",DevComment="")
+GameplayTagList=(Tag="Method.Explosive",DevComment="")
+GameplayTagList=(Tag="Method.Ok",DevComment="")
+GameplayTagList=(Tag="Method.Wrong",DevComment="")
+GameplayTagList=(Tag="Target.Correct",DevComment="")
+GameplayTagList=(Tag="Target.Police",DevComment="")
+GameplayTagList=(Tag="Target.Truck",DevComment="")
+GameplayTagList=(Tag="Target.Wrong",DevComment="")
+GameplayTagList=(Tag="Time.Correct",DevComment="")
+GameplayTagList=(Tag="Time.Ok",DevComment="")

